<a href="https://colab.research.google.com/github/SofiaGom/RegresionLogistica/blob/main/Act7_A01660774.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Actividad 7 (Regresión Logística)
##Sofía Gómez Torres A01660774

In [93]:
#importamos librerias necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [94]:
abrir = pd.read_csv("cuentas_credicel.csv", encoding = "latin")
abrir.head(5)

<ipython-input-94-d83d4867c9b9>:1: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  abrir = pd.read_csv("cuentas_credicel.csv", encoding = "latin")


folio       tag  folio_solicitud           fecha     marca  \
0      3  HDNAWQ3A               30  12/11/21 19:00       ZTE   
1      4  M418YNR4               33  12/11/21 19:15  MOTOROLA   
2      5  SZ7V3NZT               37  13/11/21 14:13       ZTE   
3      6  9I08UIQZ               38  13/11/21 15:45       ZTE   
4      7  JMF4LKYU               44  13/11/21 16:10  MOTOROLA   

                         modelo plazo  precio  enganche  descuento  ...  \
0            Blade A3 2020 RO B   26S  1949.0     780.0        0.0  ...   
1  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0        0.0  ...   
2            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
3            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
4                         G10 B   39S  4299.0    1075.0        0.0  ...   

   porc_eng  limite_credito  semana_actual  cp_cliente edad_cliente  \
0     40.02            5000             26         NaN         23.0   
1     35.01            6000             13         NaN         60.0   
2     25.01               0             74         NaN         58.0   
3     25.01            7000             13         NaN         42.0   
4     25.01            7000             74         NaN         33.0   

    cd_cliente  edo_cliente                    cd_venta edo_venta  \
0            0            0                   Tantoyuca  Veracruz   
1      PUEBLA          PUE.  Heroica Puebla de Zaragoza    Puebla   
2    TANTOYUCA         VER.                           0         0   
3  AMXTLAN PUE          NaN                    Zacatlan    Puebla   
4   TANTOYUCA          VER.                   Tantoyuca  Veracruz   

                 curp  
0  AEVM980413MVZNDR02  
1  ZALC610119MPLPRR07  
2                   0  
3  SAMJ790115MPLNRS02  
4  TEHF880707HVZRRR07  

[5 rows x 39 columns]

In [95]:
abrir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio               22735 non-null  int64  
 1   tag                 22735 non-null  object 
 2   folio_solicitud     22735 non-null  int64  
 3   fecha               22735 non-null  object 
 4   marca               22735 non-null  object 
 5   modelo              22735 non-null  object 
 6   plazo               22735 non-null  object 
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64  
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64  
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object 
 15  dis_venta           22735 non-null  object 
 16  stat

In [96]:
df = abrir.copy()

In [97]:
df.columns

Index(['folio', 'tag', 'folio_solicitud', 'fecha', 'marca', 'modelo', 'plazo',
       'precio', 'enganche', 'descuento', 'semana', 'monto_financiado',
       'costo_total', 'monto_accesorios', 'agente_venta', 'dis_venta',
       'status', 'fraude', 'empresa', 'inversion', 'pagos_realizados',
       'reautorizacion', 'fecha_ultimo_pago', 'fecha_pago_proximo',
       'status_cuenta', 'puntos', 'riesgo', 'score_buro', 'razones_buro',
       'porc_eng', 'limite_credito', 'semana_actual', 'cp_cliente',
       'edad_cliente', 'cd_cliente', 'edo_cliente', 'cd_venta', 'edo_venta',
       'curp'],
      dtype='object')

#Nulos

In [98]:
df = abrir.copy()

In [99]:
df.isnull().sum()

folio                    0
tag                      0
folio_solicitud          0
fecha                    0
marca                    0
modelo                   0
plazo                    0
precio                   0
enganche                 0
descuento                0
semana                   0
monto_financiado         0
costo_total              0
monto_accesorios         0
agente_venta             0
dis_venta                0
status                   0
fraude                   0
empresa                 13
inversion                0
pagos_realizados         0
reautorizacion           0
fecha_ultimo_pago     3356
fecha_pago_proximo    3356
status_cuenta         3314
puntos                   0
riesgo                   0
score_buro               0
razones_buro          7340
porc_eng                 0
limite_credito           0
semana_actual            0
cp_cliente            7243
edad_cliente             9
cd_cliente               0
edo_cliente              8
cd_venta                 0
e

In [100]:
df1 =df.fillna(method="bfill")

In [101]:
df1.isnull().sum().sum()

35

In [102]:
df1 = df1.fillna(method="ffill")

In [103]:
df1.isnull().sum().sum()

0

#Outliers

In [104]:
numericas = df1.select_dtypes(include=['number'])
categoricas = df1.select_dtypes(include=['object'])

In [105]:
y=numericas
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()


y= y[(y<=Limite_Superior)&(y>=Limite_Inferior)]
y.isnull().sum()

folio                  0
folio_solicitud        0
precio               110
enganche             292
descuento             17
semana               362
monto_financiado     182
costo_total          290
monto_accesorios     617
status               154
fraude              1701
inversion              0
pagos_realizados     184
reautorizacion       774
puntos                 3
riesgo                65
score_buro             0
porc_eng             275
semana_actual        178
edad_cliente          99
dtype: int64

In [106]:
y=y.fillna(round(y.mean(),1))
y.isnull().sum()

folio               0
folio_solicitud     0
precio              0
enganche            0
descuento           0
semana              0
monto_financiado    0
costo_total         0
monto_accesorios    0
status              0
fraude              0
inversion           0
pagos_realizados    0
reautorizacion      0
puntos              0
riesgo              0
score_buro          0
porc_eng            0
semana_actual       0
edad_cliente        0
dtype: int64

In [107]:
for columna in y.columns:
    df1[columna] = y[columna]

In [108]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio               22735 non-null  int64  
 1   tag                 22735 non-null  object 
 2   folio_solicitud     22735 non-null  int64  
 3   fecha               22735 non-null  object 
 4   marca               22735 non-null  object 
 5   modelo              22735 non-null  object 
 6   plazo               22735 non-null  object 
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  float64
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  float64
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object 
 15  dis_venta           22735 non-null  object 
 16  stat

#Regresión logística

Analizar 10 casos de correlación logística que existe entre diferentes variables de nuestra base de datos, aplicando la herramienta de “Regresión Logística”

In [109]:
regresion = df1.copy()

In [110]:
coeficientes = pd.DataFrame(columns=['Variable', 'Analisis', 'Precision', 'Exactitud','Sensibilidad'])

#Análisis 1

In [111]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['precio', 'descuento', 'costo_total']]
Var_Dep= df['modelo']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [112]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['A03s', 'A03', 'A03s', ..., 'A13', 'A03', 'A03'], dtype=object)

In [113]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [114]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[0] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

Precisión del modelo:
0.012122951541610779
Sensibilidad del modelo:
0.018484685460382632
Puntaje F1 del modelo:
0.01200496651015426


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Análisis 2

In [115]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['precio', 'fraude', 'costo_total']]
Var_Dep= df['marca']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [116]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Samsung', 'ZTE', 'Samsung', ..., 'ZTE', 'Samsung', 'Samsung'],
      dtype=object)

In [117]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    15    0    1    0    0    0   33]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    17    0    0    0    0    0    9]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    44    0    0    0    0    0   47]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
   102    0    0    0    0    0   19]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     1    0    0    0    0    0    1]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     7    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     5    0    0    0    0    0   19]
 [   0    0    0    0    0    0    0    4    1    0    0    0    0    0
   916    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    1    0    0    0    0    0    0
   505    0    0    0    0 

In [118]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[1] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

Precisión del modelo:
0.08484556019644407
Sensibilidad del modelo:
0.08373123297213315
Puntaje F1 del modelo:
0.05845450031662983


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Modelo 3

In [121]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df1[['enganche', 'monto_financiado', 'descuento']]
Var_Dep= df1['agente_venta']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [122]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['David Espinoza Medina', 'Nain Raymundo Mex Hau',
       'David Espinoza Medina', ..., 'David Espinoza Medina',
       'David Espinoza Medina', 'David Espinoza Medina'], dtype=object)

In [123]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [126]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[2] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precisión del modelo:
0.0
Sensibilidad del modelo:
0.0
Puntaje F1 del modelo:
0.0


#Modelo 4

In [127]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['enganche', 'semana_actual', 'porc_eng']]
Var_Dep= df['plazo']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [128]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['26S', '26S', '26S', ..., '26S', '26S', '26S'], dtype=object)

In [129]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[ 428 1464   37    1]
 [ 327 2775  135    2]
 [  80 1266  172    4]
 [   0   99   29    2]]


In [130]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[3] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

Precisión del modelo:
0.4227762726828799
Sensibilidad del modelo:
0.30172534526751876
Puntaje F1 del modelo:
0.2868766177464912


#Modelo 5

In [133]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['precio', 'riesgo', 'fraude']]
Var_Dep= df['dis_venta']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [134]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['mic0912', 'mic0912', 'mic0912', ..., 'svc001', 'mic015', 'mic015'],
      dtype=object)

In [135]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [136]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[4] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precisión del modelo:
0.000953381631005671
Sensibilidad del modelo:
0.003184640301288299
Puntaje F1 del modelo:
0.0008556663359728232


#Modelo 6

In [139]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df1[['enganche', 'precio', 'inversion']]
Var_Dep= df1['empresa']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [140]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['microtec', 'microtec', 'servicel', ..., 'servicel', 'microtec',
       'microtec'], dtype=object)

In [141]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [142]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[5] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precisión del modelo:
0.03155647905635921
Sensibilidad del modelo:
0.03467584773638585
Puntaje F1 del modelo:
0.030045224491182118


#Modelo 7

In [150]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df1[['enganche', 'reautorizacion', 'descuento']]
Var_Dep= df1['cd_cliente']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [151]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['PUEBLA', 'JOSE MARIA MORELOS', 'PUEBLA', ..., 'PUEBLA', 'PUEBLA',
       'PUEBLA'], dtype=object)

In [152]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [153]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[6] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precisión del modelo:
0.0004155399135698817
Sensibilidad del modelo:
0.0016146685769670146
Puntaje F1 del modelo:
0.0004650294262400161


#Modelo 8

In [154]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df1[['precio', 'riesgo', 'descuento']]
Var_Dep= df1['dis_venta']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [155]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['svc011', 'svc001', 'mic0912', ..., 'mic0912', 'mic0912', 'svc001'],
      dtype=object)

In [156]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [158]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[7] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precisión del modelo:
0.0011581609414494899
Sensibilidad del modelo:
0.004910945798167665
Puntaje F1 del modelo:
0.0012131759255238344


#Modelo 9

In [160]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df1[['score_buro', 'precio', 'riesgo']]
Var_Dep= df1['status_cuenta']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [161]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Mora', 'Corriente', 'Corriente', ..., 'Mora', 'Corriente',
       'Corriente'], dtype=object)

In [162]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0  743    0  264]
 [   0    0   54    0   35]
 [   0    0 2888    0  405]
 [   0    0  374    0  228]
 [   0    0  778    0 1052]]


In [163]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[8] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

Precisión del modelo:
0.22546124630702852
Sensibilidad del modelo:
0.2903750462564241
Puntaje F1 del modelo:
0.25242138273506487


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Modelo 10

In [165]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df1[['porc_eng', 'precio', 'descuento']]
Var_Dep= df1['edo_venta']

#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

#Se escalan todos los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [166]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Puebla', 'Yucatan', 'Puebla', ..., 'Puebla', 'Yucatan', 'Yucatan'],
      dtype=object)

In [167]:
#coeficientes
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   30    0    0    0    0    0    0    0    0    1
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   21    0    0    0    0    0    0    0    0    0
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    2    0    0    0    0    0    0    0    0    0
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0  115    0    0    0    0    0    0    0    0    7
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   62    0    0    0    0    0    0    0    0  113
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   23    0    0    0    0    0    0    0    0   31
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0 

In [168]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

puntaje = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntaje)

coeficientes.loc[9] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntaje,2) ]

Precisión del modelo:
0.033819827889704175
Sensibilidad del modelo:
0.054852536565472156
Puntaje F1 del modelo:
0.04045844555598414


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [170]:
coeficientes

Variable Analisis  Precision  Exactitud  Sensibilidad
0      tag        1       0.00       0.00          0.00
1      tag        1       0.08       0.08          0.06
2      tag        1       0.00       0.00          0.00
3      tag        1       0.42       0.30          0.29
4      tag        1       0.00       0.00          0.00
5      tag        1       0.03       0.03          0.03
6      tag        1       0.00       0.00          0.00
7      tag        1       0.00       0.00          0.00
8      tag        1       0.23       0.29          0.25
9      tag        1       0.03       0.05          0.04